<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddIsAutogeneratedFieldToLeads extends Migration
{
    public function up()
    {
        Schema::table('leads', function (Blueprint $table) {
            $table->boolean('is_autogenerated')->after('is_test');
        });
    }

    public function down()
    {
        Schema::table('leads', function (Blueprint $table) {
            //
        });
    }
}
