<?php
declare(strict_types=1);

return array(
    array('locale_id' => '5', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteaes', 'offer_id' => '1', 'target_id' => '1', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1, 'is_back_action' => 1, 'is_back_call' => 1, 'is_vibrate_on_mobile' => 1,),
    array('locale_id' => '5', 'title' => 'Choco Lite v.2', 'subdomain' => 'chocolitemes', 'offer_id' => '1', 'target_id' => '1', 'is_private' => '0', 'is_mobile' => '1', 'is_active' => '1', 'is_responsive' => '0', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '5', 'title' => 'Choco Lite v.3', 'subdomain' => 'chocoliteces', 'offer_id' => '1', 'target_id' => '1', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '8', 'title' => 'Choco Lite v.1 ', 'subdomain' => 'chocoliteait', 'offer_id' => '1', 'target_id' => '2', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '8', 'title' => 'Choco Lite v.2', 'subdomain' => 'chocolitemit', 'offer_id' => '1', 'target_id' => '2', 'is_private' => '0', 'is_mobile' => '1', 'is_active' => '1', 'is_responsive' => '0', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '8', 'title' => 'Choco Lite v.3', 'subdomain' => 'chocolitecit', 'offer_id' => '1', 'target_id' => '2', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '12', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocolitegra', 'offer_id' => '1', 'target_id' => '3', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '12', 'title' => 'Choco Lite v.4', 'subdomain' => 'chocolitedgr', 'offer_id' => '1', 'target_id' => '3', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '11', 'title' => 'Choco Lite v.5', 'subdomain' => 'chocolitehub', 'offer_id' => '1', 'target_id' => '4', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '11', 'title' => 'Choco Lite v.3', 'subdomain' => 'chocolitechu', 'offer_id' => '1', 'target_id' => '4', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '11', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteahu', 'offer_id' => '1', 'target_id' => '4', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '14', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteabg', 'offer_id' => '1', 'target_id' => '5', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '14', 'title' => 'Choco Lite v.3', 'subdomain' => 'chocolitecbg', 'offer_id' => '1', 'target_id' => '5', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '14', 'title' => 'Choco Lite v.4', 'subdomain' => 'chocolitedbg', 'offer_id' => '1', 'target_id' => '5', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '7', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocolitearo', 'offer_id' => '1', 'target_id' => '6', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '7', 'title' => 'Choco Lite v.3', 'subdomain' => 'chocolitecro', 'offer_id' => '1', 'target_id' => '6', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '7', 'title' => 'Choco Lite v.4', 'subdomain' => 'chocolitedro', 'offer_id' => '1', 'target_id' => '6', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '4', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocolitepla', 'offer_id' => '1', 'target_id' => '7', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '9', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteapt', 'offer_id' => '1', 'target_id' => '8', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '9', 'title' => 'Choco Lite v.5', 'subdomain' => 'chocoliteept', 'offer_id' => '1', 'target_id' => '8', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '15', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteacz', 'offer_id' => '1', 'target_id' => '9', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '15', 'title' => 'Choco Lite v.2', 'subdomain' => 'chocolitebcz', 'offer_id' => '1', 'target_id' => '9', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
    array('locale_id' => '16', 'title' => 'Choco Lite v.1', 'subdomain' => 'chocoliteask', 'offer_id' => '1', 'target_id' => '10', 'is_private' => '0', 'is_mobile' => '0', 'is_active' => '1', 'is_responsive' => '1', 'is_advertiser_viewable' => '1', 'is_address_on_success' => '0', 'is_email_on_success' => '0', 'is_custom_success' => '0', 'type' => 'cod', 'has_thumb' => 1,),
);
